[package]
name = "future-ex"
version = "0.1.0"
edition = "2021"

[lib]
name = "future_ex"

[dependencies]
anyhow             = "1.0"
thiserror          = "1.0"
tokio              = { version = "1.0", features = ["full"] }
tracing            = "0.1.26"
tracing-subscriber = "0.2.19"
